// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package repository

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Session struct {
	ID        int64              `json:"id"`
	Jti       string             `json:"jti"`
	UserID    int32              `json:"user_id"`
	IssuedAt  pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	UserAgent pgtype.Text        `json:"user_agent"`
	ClientIp  pgtype.Text        `json:"client_ip"`
}

type User struct {
	ID           int32              `json:"id"`
	Username     string             `json:"username"`
	Email        string             `json:"email"`
	FullName     pgtype.Text        `json:"full_name"`
	PasswordHash string             `json:"password_hash"`
	IsActive     pgtype.Bool        `json:"is_active"`
	Role         pgtype.Text        `json:"role"`
	LastLogin    pgtype.Timestamptz `json:"last_login"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
