// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries_sessions.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (jti, user_id, expires_at, user_agent, client_ip)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, jti, user_id, issued_at, expires_at, revoked_at, user_agent, client_ip
`

type CreateSessionParams struct {
	Jti       string             `json:"jti"`
	UserID    int32              `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UserAgent pgtype.Text        `json:"user_agent"`
	ClientIp  pgtype.Text        `json:"client_ip"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.Jti,
		arg.UserID,
		arg.ExpiresAt,
		arg.UserAgent,
		arg.ClientIp,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Jti,
		&i.UserID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.ClientIp,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions
WHERE expires_at < CURRENT_TIMESTAMP
   OR revoked_at IS NOT NULL
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const getSessionByJTI = `-- name: GetSessionByJTI :one
SELECT id, jti, user_id, issued_at, expires_at, revoked_at, user_agent, client_ip
FROM sessions
WHERE jti = $1
LIMIT 1
`

func (q *Queries) GetSessionByJTI(ctx context.Context, jti string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByJTI, jti)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Jti,
		&i.UserID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.UserAgent,
		&i.ClientIp,
	)
	return i, err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE sessions
SET revoked_at = CURRENT_TIMESTAMP
WHERE user_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID int32) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = CURRENT_TIMESTAMP
WHERE jti = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, jti string) error {
	_, err := q.db.Exec(ctx, revokeSession, jti)
	return err
}
