// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package repository

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveUsers = `-- name: CountActiveUsers :one
SELECT COUNT(*) FROM users
WHERE is_active = true
`

func (q *Queries) CountActiveUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUsersByRole = `-- name: CountUsersByRole :one
SELECT COUNT(*) FROM users
WHERE role = $1
`

func (q *Queries) CountUsersByRole(ctx context.Context, role pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersByRole, role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, username, full_name, role, is_active)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, username, full_name, password_hash, is_active, role, last_login, created_at, updated_at
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	PasswordHash string      `json:"password_hash"`
	Username     string      `json:"username"`
	FullName     pgtype.Text `json:"full_name"`
	Role         pgtype.Text `json:"role"`
	IsActive     pgtype.Bool `json:"is_active"`
}

type CreateUserRow struct {
	ID           int32              `json:"id"`
	Email        string             `json:"email"`
	Username     string             `json:"username"`
	FullName     pgtype.Text        `json:"full_name"`
	PasswordHash string             `json:"password_hash"`
	IsActive     pgtype.Bool        `json:"is_active"`
	Role         pgtype.Text        `json:"role"`
	LastLogin    pgtype.Timestamptz `json:"last_login"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.Username,
		arg.FullName,
		arg.Role,
		arg.IsActive,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.FullName,
		&i.PasswordHash,
		&i.IsActive,
		&i.Role,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveUsers = `-- name: GetActiveUsers :many
SELECT id, email, username, full_name, is_active, role, last_login, created_at, updated_at
FROM users
WHERE is_active = true
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetActiveUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetActiveUsersRow struct {
	ID        int32              `json:"id"`
	Email     string             `json:"email"`
	Username  string             `json:"username"`
	FullName  pgtype.Text        `json:"full_name"`
	IsActive  pgtype.Bool        `json:"is_active"`
	Role      pgtype.Text        `json:"role"`
	LastLogin pgtype.Timestamptz `json:"last_login"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetActiveUsers(ctx context.Context, arg GetActiveUsersParams) ([]GetActiveUsersRow, error) {
	rows, err := q.db.Query(ctx, getActiveUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetActiveUsersRow{}
	for rows.Next() {
		var i GetActiveUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.FullName,
			&i.IsActive,
			&i.Role,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInactiveUsers = `-- name: GetInactiveUsers :many
SELECT id, email, username, full_name, is_active, role, last_login, created_at, updated_at
FROM users
WHERE is_active = false
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetInactiveUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetInactiveUsersRow struct {
	ID        int32              `json:"id"`
	Email     string             `json:"email"`
	Username  string             `json:"username"`
	FullName  pgtype.Text        `json:"full_name"`
	IsActive  pgtype.Bool        `json:"is_active"`
	Role      pgtype.Text        `json:"role"`
	LastLogin pgtype.Timestamptz `json:"last_login"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetInactiveUsers(ctx context.Context, arg GetInactiveUsersParams) ([]GetInactiveUsersRow, error) {
	rows, err := q.db.Query(ctx, getInactiveUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetInactiveUsersRow{}
	for rows.Next() {
		var i GetInactiveUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.FullName,
			&i.IsActive,
			&i.Role,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, full_name, password_hash, is_active, role, last_login, created_at, updated_at
FROM users
WHERE email = $1
LIMIT 1
`

type GetUserByEmailRow struct {
	ID           int32              `json:"id"`
	Email        string             `json:"email"`
	Username     string             `json:"username"`
	FullName     pgtype.Text        `json:"full_name"`
	PasswordHash string             `json:"password_hash"`
	IsActive     pgtype.Bool        `json:"is_active"`
	Role         pgtype.Text        `json:"role"`
	LastLogin    pgtype.Timestamptz `json:"last_login"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.FullName,
		&i.PasswordHash,
		&i.IsActive,
		&i.Role,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmailAndPassword = `-- name: GetUserByEmailAndPassword :one
SELECT id, email, username, full_name, is_active, role, last_login, created_at, updated_at
FROM users
WHERE email = $1 AND password_hash = $2
LIMIT 1
`

type GetUserByEmailAndPasswordParams struct {
	Email        string `json:"email"`
	PasswordHash string `json:"password_hash"`
}

type GetUserByEmailAndPasswordRow struct {
	ID        int32              `json:"id"`
	Email     string             `json:"email"`
	Username  string             `json:"username"`
	FullName  pgtype.Text        `json:"full_name"`
	IsActive  pgtype.Bool        `json:"is_active"`
	Role      pgtype.Text        `json:"role"`
	LastLogin pgtype.Timestamptz `json:"last_login"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByEmailAndPassword(ctx context.Context, arg GetUserByEmailAndPasswordParams) (GetUserByEmailAndPasswordRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmailAndPassword, arg.Email, arg.PasswordHash)
	var i GetUserByEmailAndPasswordRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.FullName,
		&i.IsActive,
		&i.Role,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, username, full_name, password_hash, is_active, role, last_login, created_at, updated_at
FROM users
WHERE id = $1
LIMIT 1
`

type GetUserByIDRow struct {
	ID           int32              `json:"id"`
	Email        string             `json:"email"`
	Username     string             `json:"username"`
	FullName     pgtype.Text        `json:"full_name"`
	PasswordHash string             `json:"password_hash"`
	IsActive     pgtype.Bool        `json:"is_active"`
	Role         pgtype.Text        `json:"role"`
	LastLogin    pgtype.Timestamptz `json:"last_login"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int32) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.FullName,
		&i.PasswordHash,
		&i.IsActive,
		&i.Role,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, username, full_name, password_hash, is_active, role, last_login, created_at, updated_at
FROM users
WHERE username = $1
LIMIT 1
`

type GetUserByUsernameRow struct {
	ID           int32              `json:"id"`
	Email        string             `json:"email"`
	Username     string             `json:"username"`
	FullName     pgtype.Text        `json:"full_name"`
	PasswordHash string             `json:"password_hash"`
	IsActive     pgtype.Bool        `json:"is_active"`
	Role         pgtype.Text        `json:"role"`
	LastLogin    pgtype.Timestamptz `json:"last_login"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.FullName,
		&i.PasswordHash,
		&i.IsActive,
		&i.Role,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUsersByRole = `-- name: GetUsersByRole :many
SELECT id, email, username, full_name, is_active, role, last_login, created_at, updated_at
FROM users
WHERE role = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetUsersByRoleParams struct {
	Role   pgtype.Text `json:"role"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

type GetUsersByRoleRow struct {
	ID        int32              `json:"id"`
	Email     string             `json:"email"`
	Username  string             `json:"username"`
	FullName  pgtype.Text        `json:"full_name"`
	IsActive  pgtype.Bool        `json:"is_active"`
	Role      pgtype.Text        `json:"role"`
	LastLogin pgtype.Timestamptz `json:"last_login"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUsersByRole(ctx context.Context, arg GetUsersByRoleParams) ([]GetUsersByRoleRow, error) {
	rows, err := q.db.Query(ctx, getUsersByRole, arg.Role, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUsersByRoleRow{}
	for rows.Next() {
		var i GetUsersByRoleRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.FullName,
			&i.IsActive,
			&i.Role,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, username, full_name, is_active, role, last_login, created_at, updated_at
FROM users
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	ID        int32              `json:"id"`
	Email     string             `json:"email"`
	Username  string             `json:"username"`
	FullName  pgtype.Text        `json:"full_name"`
	IsActive  pgtype.Bool        `json:"is_active"`
	Role      pgtype.Text        `json:"role"`
	LastLogin pgtype.Timestamptz `json:"last_login"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.FullName,
			&i.IsActive,
			&i.Role,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByID = `-- name: ListUsersByID :many
SELECT id, email, username, full_name, is_active, role, last_login, created_at, updated_at
FROM users
ORDER BY id ASC
LIMIT $1 OFFSET $2
`

type ListUsersByIDParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersByIDRow struct {
	ID        int32              `json:"id"`
	Email     string             `json:"email"`
	Username  string             `json:"username"`
	FullName  pgtype.Text        `json:"full_name"`
	IsActive  pgtype.Bool        `json:"is_active"`
	Role      pgtype.Text        `json:"role"`
	LastLogin pgtype.Timestamptz `json:"last_login"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListUsersByID(ctx context.Context, arg ListUsersByIDParams) ([]ListUsersByIDRow, error) {
	rows, err := q.db.Query(ctx, listUsersByID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersByIDRow{}
	for rows.Next() {
		var i ListUsersByIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.FullName,
			&i.IsActive,
			&i.Role,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreUser = `-- name: RestoreUser :exec
UPDATE users
SET is_active = true, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) RestoreUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, restoreUser, id)
	return err
}

const searchUsers = `-- name: SearchUsers :many
SELECT id, email, username, full_name, is_active, role, last_login, created_at, updated_at
FROM users
WHERE username ILIKE '%' || $1 || '%'
   OR email ILIKE '%' || $1 || '%'
   OR full_name ILIKE '%' || $1 || '%'
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type SearchUsersParams struct {
	Column1 pgtype.Text `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type SearchUsersRow struct {
	ID        int32              `json:"id"`
	Email     string             `json:"email"`
	Username  string             `json:"username"`
	FullName  pgtype.Text        `json:"full_name"`
	IsActive  pgtype.Bool        `json:"is_active"`
	Role      pgtype.Text        `json:"role"`
	LastLogin pgtype.Timestamptz `json:"last_login"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SearchUsers(ctx context.Context, arg SearchUsersParams) ([]SearchUsersRow, error) {
	rows, err := q.db.Query(ctx, searchUsers, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchUsersRow{}
	for rows.Next() {
		var i SearchUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.FullName,
			&i.IsActive,
			&i.Role,
			&i.LastLogin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteUser = `-- name: SoftDeleteUser :exec
UPDATE users
SET is_active = false, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) SoftDeleteUser(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, softDeleteUser, id)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET username = $2,
    full_name = $3,
    email = $4,
    role = $5,
    is_active = $6,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, email, username, full_name, password_hash, is_active, role, last_login, created_at, updated_at
`

type UpdateUserParams struct {
	ID       int32       `json:"id"`
	Username string      `json:"username"`
	FullName pgtype.Text `json:"full_name"`
	Email    string      `json:"email"`
	Role     pgtype.Text `json:"role"`
	IsActive pgtype.Bool `json:"is_active"`
}

type UpdateUserRow struct {
	ID           int32              `json:"id"`
	Email        string             `json:"email"`
	Username     string             `json:"username"`
	FullName     pgtype.Text        `json:"full_name"`
	PasswordHash string             `json:"password_hash"`
	IsActive     pgtype.Bool        `json:"is_active"`
	Role         pgtype.Text        `json:"role"`
	LastLogin    pgtype.Timestamptz `json:"last_login"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Username,
		arg.FullName,
		arg.Email,
		arg.Role,
		arg.IsActive,
	)
	var i UpdateUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.FullName,
		&i.PasswordHash,
		&i.IsActive,
		&i.Role,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserIsActive = `-- name: UpdateUserIsActive :exec
UPDATE users
SET is_active = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
`

type UpdateUserIsActiveParams struct {
	ID       int32       `json:"id"`
	IsActive pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpdateUserIsActive(ctx context.Context, arg UpdateUserIsActiveParams) error {
	_, err := q.db.Exec(ctx, updateUserIsActive, arg.ID, arg.IsActive)
	return err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, email, username, full_name, password_hash, is_active, role, last_login, created_at, updated_at
`

type UpdateUserRoleParams struct {
	ID   int32       `json:"id"`
	Role pgtype.Text `json:"role"`
}

type UpdateUserRoleRow struct {
	ID           int32              `json:"id"`
	Email        string             `json:"email"`
	Username     string             `json:"username"`
	FullName     pgtype.Text        `json:"full_name"`
	PasswordHash string             `json:"password_hash"`
	IsActive     pgtype.Bool        `json:"is_active"`
	Role         pgtype.Text        `json:"role"`
	LastLogin    pgtype.Timestamptz `json:"last_login"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (UpdateUserRoleRow, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.ID, arg.Role)
	var i UpdateUserRoleRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.FullName,
		&i.PasswordHash,
		&i.IsActive,
		&i.Role,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
